[package]
name = "npm-sept-2025-incident-scan"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
regex = "1.0"
rayon = "1.7"
colored = "2.0"
glob = "0.3"
chrono = { version = "0.4", features = ["serde"] }
